### PR TITLE
Notepad++ rough draft

### PR DESCRIPTION
**Pull request by DisarmedRemo66**
Continued updating documentation

### CODE REVIEW

**Comment by bjones1** [comment]
What does this PR do? From what can tell, it adds a command to read a file to Notepad++, but I don't see how that's related to the project.

**Comment by DisarmedRemo66** [comment]
> What does this PR do? From what can tell, it adds a command to read a file to Notepad++, but I don't see how that's related to the project.

This was our best attempt at incorporating a way for the plugin to use a function call to pull data from a file (i.e a word document or notepad document)

**Comment by bjones1** [comment]
OK, thanks. The intent was to pull data from whatever file Notepad++ was currently editing, but this helps me understand what the PR does.

**Comment by bjones1** [comment]
Merged in 3debe413.

**Pull request closed without merging**
